### ISSUE TITLE
Compilation fails with zig 0.14-dev

### ISSUE THREAD

**Issue by begoon** [adia-dev/chroma-zig#1]
```
run
└─ run main
   └─ zig build-exe main Debug native 1 errors
/Users/alexander/.cache/zig/p/12209a8a991121bba3b21f31d275588690dc7c0d7fa9c361fd892e782dd88e0fb2ba/src/lib.zig:100:46: error: no field named 'Enum' in union 'builtin.Type'
                    for (@typeInfo(AnsiCode).Enum.fields) |field| {
                                             ^~~~
/Users/alexander/.zig/lib/std/builtin.zig:556:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
main.zig:17:34: note: called from here
    std.debug.print(chroma.format("{blue}{underline}Eventually{reset}, the {red}formatting{reset} looks like {130;43;122}{s}!\n"), .{"this"});
                    ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    main: /Users/alexander/.zig/lib/std/start.zig:617:37
    comptime: /Users/alexander/.zig/lib/std/start.zig:58:30
    2 reference(s) hidden; use '-freference-trace=4' to see all references
```

**Comment by adia-dev** [comment]
Well breaking change in the new [0.14](https://github.com/lalinsky/msgpack.zig/pull/2#issue-2734213508) version 🤷🏿 
I fixed it and pushed it on the [0.14.x](https://github.com/adia-dev/chroma-zig/tree/0.14.x) branch.

You can use:

```bash
zig fetch --save https://github.com/adia-dev/chroma-zig/archive/refs/heads/0.14.x.tar.gz
```

Don't hesitate to tell me if it works or if you still have issues with it 😄

**Comment by begoon** [comment]
@adia-dev I have just tested, and everything works with 0.14-dev. Thanks.

**Comment by begoon** [comment]
Fixed as described by @adia-dev above.
